### PR TITLE
Javin - Refactor announcements PUT operation

### LINKED ISSUE #30: Refactor "Put" operation for Announcements
The "Put" operation for editing announcements was poorly implemented in the legacy code and does not work, even on Swagger, since it has an issue parsing the localDateTime parameters. 
Normally, Put operations look like this, where you pass in a whole object:
image
But the existsing Announcements put operation is:
image
Which is weird. It also makes another issue - adding the Edit operation frontend - much harder to implement and diagnose. Thank you to Sangita for helping me discover this issue.
Tasks:
- [x] Edit the Announcements controller so that Put works on swagger for valid date-time values.
- [x] Refactor the tests for the AnnouncementsController so that they pass with the new version of PUT.
- [x] 100% line coverage with new tests.
- [x] 100% mutation coverage with new tests.

### PR DESCRIPTION
**Pull request by jzipkin1812**
## Overview

As described in #30 the Put operation for announcements was implemented poorly. 
- It now properly takes a whole object as its response body. It no longer fails to parse date/time strings. 
- The PUT operation for announcements now works the same as the PUT operation for commons, and it's weird that they worked totally different before.
- Upon trying to edit an announcement that doesn't exist, PUT correctly returns an error 404, not 400. For reference, the previous implementation did things like this for every error, naming them all as BadRequest for some reason when they clearly should have had a different response code:
image
This made Swagger super hard to test and diagnose!
- PUT throws an error 403 (Forbidden) if your permissions are not correct. Before, there were situations where this would throw an error 400.
- Doesn't throw an undocumented response code 204 anymore upon receiving bad input. That wasn't helpful.
- The tests have all been overhauled to support the new changes.

## Screenshots

PUT looks like this now on Swagger. I didn't edit the frontend for this issue.
image
And here's an example 404 error:
image

## Deployment
https://happycows-dev-jzipkin1812.dokku-12.cs.ucsb.edu

## Validation 

On the deployment, play around with the PUT operation for announcements on Swagger. You should be able to see that errors in the structure of the request will be caught - for example, you shouldn't be able to edit an Announcement to have an empty text field or a start date that occurs after its end date.
## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 

## Linked Issues

Closes #30.

### CODE REVIEW

**Review by pconrad — CHANGES_REQUESTED** [review]
Mostly LGTM... I see one place where we can tighten up a potential security issue, and also simplify the code a bit.

See below..

File: src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java [hunk 1]
```diff
@@ -133,54 +142,70 @@ public ResponseEntity<Object> getAnnouncementById(@Parameter(description = "The
     @PreAuthorize("hasAnyRole('ROLE_USER', 'ROLE_ADMIN')")
```
Comment (pconrad) [inline src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java]: I think it was actually a mistake before to let "any user" update announcements.  That really should be reserved only for Admins, especially since at the moment, until we restrict game via the course roster, literally anyone with a Google account could log in and be a user.   The potential for bad outcomes (i.e. someone sabotaging the game) is high.
```suggestion
    @PreAuthorize("hasRole( 'ROLE_ADMIN')")
```

Plus this simplifies your code later on.

File: src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java [hunk 2]
```diff
@@ -133,54 +142,70 @@ public ResponseEntity<Object> getAnnouncementById(@Parameter(description = "The
...
+            log.info("User is not an admin, checking if they're in the relevant commons");
+            Optional<UserCommons> userCommonsLookup = userCommonsRepository.findByCommonsIdAndUserId(commonsId, userId);
 
-        // Save the announcement
-        announcementRepository.save(announcementObj);
-        return ResponseEntity.ok(announcementObj);
+            if (!userCommonsLookup.isPresent()) {
+                return ResponseEntity.status(HttpStatus.FORBIDDEN).build();
+            }
+        }
```
Comment (pconrad) [inline src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java]: Might not need this anymore if we change PUT to ADMIN only?

Also the comment about `showChat` is maybe a copy/paste error?

**Review by pconrad — CHANGES_REQUESTED** [review]
This is really nice work. Just one issue that's a catch of a mistake that was already in the code base...

File: src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java (hunk 1 above)
Comment (jzipkin1812) [reply src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java]: This makes sense to me, I'll change the code

File: src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java (hunk 2 above)
Comment (jzipkin1812) [reply src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java]: Yes, I'll change the comment / simplify

**Comment by jzipkin1812** [comment]
Simplification + security done, users can't edit announcements anymore

**Review by mayarosenbaum — APPROVED** [review]
Looks good! Just finished playing around with the operation and it seems to be catching all errors.

**Review by pconrad — APPROVED** [review]
LGTM!
